<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kheprx.BaseBackend.Health.Domain\Kheprx.BaseBackend.Health.Domain.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\Kheprx.BaseBackend.SharedKernel\Kheprx.BaseBackend.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Kheprx.BaseBackend.Health.Infrastructure" />
    <InternalsVisibleTo Include="Kheprx.BaseBackend.Health.UnitTests" />
  </ItemGroup>
</Project>
