// <auto-generated />
using System;
using Kheprx.BaseBackend.Health.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kheprx.BaseBackend.Health.Infrastructure.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    [Migration("20260918134550_CreateHealthReadingTable")]
    partial class CreateHealthReadingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("health")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kheprx.BaseBackend.Health.Domain.Entities.HealthReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalTestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SwimmerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalTestId");

                    b.ToTable("health_reading", "health");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Health.Domain.Entities.MedicalTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UpperBound")
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.ToTable("medical_test", "health");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Health.Domain.Entities.HealthReading", b =>
                {
                    b.HasOne("Kheprx.BaseBackend.Health.Domain.Entities.MedicalTest", null)
                        .WithMany()
                        .HasForeignKey("MedicalTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
