// <auto-generated />
using System;
using Kheprx.BaseBackend.Championships.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kheprx.BaseBackend.Championships.Infrastructure.Migrations
{
    [DbContext(typeof(ChampionshipsDbContext))]
    [Migration("20260923230234_CreateRaceResultTable")]
    partial class CreateRaceResultTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("championships")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kheprx.BaseBackend.Championships.Domain.Entities.ChampionshipEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SwimmerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SwimmerId")
                        .IsUnique();

                    b.ToTable("championship_enrollment", "championships");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Championships.Domain.Entities.CompetitionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DayDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LabelAr")
                        .HasColumnType("text");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("competition_day", "championships");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Championships.Domain.Entities.CompetitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LocationAr")
                        .HasColumnType("text");

                    b.Property<string>("LocationEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("competition_event", "championships");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Championships.Domain.Entities.RaceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SwimmerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceSessionId", "SwimmerId")
                        .IsUnique();

                    b.ToTable("race_assignment", "championships");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Championships.Domain.Entities.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPersonalBest")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SwimmerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceSessionId", "SwimmerId")
                        .IsUnique();

                    b.ToTable("race_result", "championships");
                });

            modelBuilder.Entity("Kheprx.BaseBackend.Championships.Domain.Entities.RaceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DistanceId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("StrokeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("race_session", "championships");
                });
#pragma warning restore 612, 618
        }
    }
}
