// <auto-generated />
using System;
using Kheprx.BaseBackend.Attendance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kheprx.BaseBackend.Attendance.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260922230203_CreateAttendanceRecordTable")]
    partial class CreateAttendanceRecordTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attendance")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kheprx.BaseBackend.Attendance.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoachNoteAr")
                        .HasColumnType("text");

                    b.Property<string>("CoachNoteEn")
                        .HasColumnType("text");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SwimmerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SwimmerId", "SessionDate")
                        .IsUnique();

                    b.ToTable("attendance_record", "attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
