<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Kheprx.BaseBackend.Api\Kheprx.BaseBackend.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Kheprx.BaseBackend.Identity.Application\Kheprx.BaseBackend.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Health\Kheprx.BaseBackend.Health.Application\Kheprx.BaseBackend.Health.Application.csproj" />
  </ItemGroup>
</Project>
